name: technical_assessment_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.1
  dio: ^5.4.3+1
  modal_progress_hud_nsn: ^0.5.1
  another_flushbar: ^1.12.30
  flutter_custom_clippers: ^2.1.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/fonts/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
        style: normal
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
        style: normal
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
        style: normal
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
        style: normal
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
        style: normal
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
        style: normal
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
        style: normal
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
        style: normal
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
        style: normal

